### ISSUE TITLE
Gaussian late initialization notebook is missing ?

### ISSUE THREAD

**Issue by beniz** [gabrielraya/symmetry_breaking_diffusion_models#1]
Very interesting paper and work, thanks for this! FYI, the gls notebook example appears to be missing.

Here: https://github.com/gabrielraya/symmetry_breaking_diffusion_models/blob/main/notebooks/gaussian_late_initalization.ipynb

**Comment by gabrielraya** [comment]
@beniz Thanks for your interest in our paper!  I have updated the link in the readme file or directly [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1ONQgBFye2MF9YSHszNvYApzqKYmh_JpA?usp=sharing)
If you find any other issues please do let me know!

**Comment by beniz** [comment]
Thanks @gabrielraya for the notebook example.

I understand that the gls scheme is a by-product of the great analysis in the paper and may not be central to it. I believe it'd be interesting to get more details on the mean and covariance matrix estimation that is collected prior to fitting the Gaussian for gls though.

The sentence in the paper 'This scheme involves estimating the mean and covariance matrix of noise-corrupted dataset at the initialization time and utilizing the resulting Gaussian distribution as the initialization
point' isn't exactly clear to me :) 
The notebook loads the previously saved approx stats, but does not fully expose the sample collection scheme. I'd be interested in the details, hopefully others may be as well!

**Comment by gabrielraya** [comment]
@beniz  I will add a working example of this to the notebook. I will let you know as soon is ready.  Thanks for your feedback!
 For now, you can check/use function `def gauss_approx_stats(config, stats_dir="assets/stats_gauss_approx", t_start=None):` [here](https://github.com/gabrielraya/symmetry_breaking_diffusion_models/blob/main/fast_sampler.py#L82C1-L82C1)

**Comment by gabrielraya** [comment]
@beniz I updated the Colab Notebook with a CIFAR10 example where  the approximated Gaussian distribution is computed as well. Please let me know if there is any other issue with the notebook, otherwise I will soon close this issue!

**Comment by beniz** [comment]
Thanks @gabrielraya very useful!
