### ISSUE TITLE
About the FID in Figure 4

### ISSUE THREAD

**Issue by luocfprime** [gabrielraya/symmetry_breaking_diffusion_models#3]
Hello, thanks for the insightful work! 

I have a question about the evaluation of FID scores in Figure 4. Is the FID score measured on noisy images $x_t$ or on the conditional expectation $x_0^{(t)} = \frac{1}{\sqrt{\alpha}} (x_t - \sqrt{1-\alpha} \epsilon_\theta)$ ?

<img width="777" alt="image" src="https://github.com/gabrielraya/symmetry_breaking_diffusion_models/assets/79003314/06abe6e4-a12b-4323-adeb-9728ddcb1941">

**Comment by gabrielraya** [comment]
Hello @fkcptlst sorry for the late reply. The FID is only evaluated on the generated samples $x_0$. You first generated the samples either using the ancestral sampler or any other fast sampler, such as DDIM, and then evaluate the model on those generated samples.

**Comment by luocfprime** [comment]
Thank you for replying. Now I get it! Closing this issue as resolved.
